/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentsSuccessRouteImport } from './routes/payments/success'
import { Route as PaymentsCancelRouteImport } from './routes/payments/cancel'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsSuccessRoute = PaymentsSuccessRouteImport.update({
  id: '/payments/success',
  path: '/payments/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsCancelRoute = PaymentsCancelRouteImport.update({
  id: '/payments/cancel',
  path: '/payments/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payments/cancel': typeof PaymentsCancelRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/app': typeof AuthAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payments/cancel': typeof PaymentsCancelRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/app': typeof AuthAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/payments/cancel': typeof PaymentsCancelRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/_auth/app/': typeof AuthAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/payments/cancel' | '/payments/success' | '/app'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/payments/cancel' | '/payments/success' | '/app'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/payments/cancel'
    | '/payments/success'
    | '/_auth/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PaymentsCancelRoute: typeof PaymentsCancelRoute
  PaymentsSuccessRoute: typeof PaymentsSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/success': {
      id: '/payments/success'
      path: '/payments/success'
      fullPath: '/payments/success'
      preLoaderRoute: typeof PaymentsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/cancel': {
      id: '/payments/cancel'
      path: '/payments/cancel'
      fullPath: '/payments/cancel'
      preLoaderRoute: typeof PaymentsCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PaymentsCancelRoute: PaymentsCancelRoute,
  PaymentsSuccessRoute: PaymentsSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
