#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30

>&2 echo 'PostgreSQL is available'

if ! python /app/manage.py migrate --check; then
    >&2 echo 'Running migrations'
    python /app/manage.py migrate --noinput
fi

>&2 echo 'Starting celery beat'


exec celery -A config.celery beat -l INFO
